### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by wdibi** [voronianski/simon-le-bottle#1]
Hi, can you help be with the setup? I am having trouble setting up the webhook on Facebook's end. Help much appreciated!

**Comment by voronianski** [comment]
@wdibi I will write a brief overview today, stay tuned!

**Comment by wdibi** [comment]
Thank you!

**Comment by voronianski** [comment]
@wdibi check this - https://github.com/voronianski/simon-le-bottle/blob/master/GUIDE.md
